name: wakatime

on: 
  workflow_dispatch:
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_WAKATIME }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required


